### ISSUE TITLE
I broke the CICD pipeline

### ISSUE THREAD

**Issue by JocelynYH** [bgreenawald/bananagrams#63]
One of my preivous commits (https://github.com/bgreenawald/bananagrams/commit/91424bbe047b7c735cc7f21723a20709193a9489) broke the pipeline's tests.  I made trivial (or so I thought) changes to the frontend.  How can I go about troubleshooting? @bgreenawald

**Comment by bgreenawald** [comment]
This wasn't you. I had temporarily removed the Chalkful AWS environment since it seemed like we were focusing on Radgab, so the deployment pipeline had nowhere to...... well, deploy. I've got the environment back up, so it should be good to go.
